export const sharedTranslations: Record<string, {en: string; zh: string}> = {
'Utama': {en:'Home',zh:'首页'},'Laman Utama': {en:'Home',zh:'首页'},'Tentang Kami':{en:'About Us',zh:'关于我们'},'Servis':{en:'Services',zh:'服务'},'Perkhidmatan Kami':{en:'Our Services',zh:'我们的服务'},'Portfolio':{en:'Portfolio',zh:'工程项目'},'Hubungi':{en:'Contact',zh:'联系我们'},'Semua':{en:'All',zh:'全部'},
'Saliran':{en:'Drainage',zh:'排水'},'Rumah':{en:'Housing',zh:'住宅'},'Jambatan':{en:'Bridges',zh:'桥梁'},'Pam/Blower/STP':{en:'Pumps/Blowers/STP',zh:'水泵／鼓风机／污水处理'},
'Profesionalisme':{en:'Professionalism',zh:'专业精神'},'Fleksibel':{en:'Flexibility',zh:'灵活性'},'Inovasi':{en:'Innovation',zh:'创新'},
'Melaka':{en:'Melaka',zh:'马六甲'},'Johor':{en:'Johor',zh:'柔佛'},'Gambang':{en:'Gambang',zh:'甘孟'},'Pahang':{en:'Pahang',zh:'彭亨'},'Ipoh':{en:'Ipoh',zh:'怡保'},'Perak':{en:'Perak',zh:'霹雳'},'Rawang':{en:'Rawang',zh:'万挠'},'Selangor':{en:'Selangor',zh:'雪兰莪'},'Terengganu':{en:'Terengganu',zh:'登嘉楼'},
'Pembinaan Bangunan & Kilang':{en:'Building & Factory Construction',zh:'建筑与厂房施工'},'Perlindungan Papak (Slab) Gas':{en:'Gas Pipeline Protection Slabs',zh:'燃气管道保护板'},'Servis Pam, Air Blower & Loji STP':{en:'Pumps, Air Blowers & STP Services',zh:'水泵、鼓风机与污水处理服务'},
'Bahasa Melayu (Malaysia)':{en:'English',zh:'简体中文'},'Tutup menu navigasi':{en:'Close navigation menu',zh:'关闭导航菜单'},'Buka menu navigasi':{en:'Open navigation menu',zh:'打开导航菜单'},
'Pembinaan Bangunan & Rumah':{en:'Building & Housing Construction',zh:'建筑与住宅施工'},'Jambatan & Kerja Awam':{en:'Bridges & Civil Works',zh:'桥梁与土木工程'},'Saliran & Pembetungan':{en:'Drainage & Sewerage',zh:'排水与污水系统'},'Perlindungan Slab Gas':{en:'Gas Protection Slabs',zh:'燃气管道保护板'},'Ubah Suai Rumah':{en:'Home Renovation',zh:'住宅翻新'},'Lain-lain Kerja Kejuruteraan':{en:'Other Engineering Works',zh:'其他工程'},
'Kontraktor Pembinaan & Kejuruteraan Awam':{en:'Construction & Civil Engineering Contractor',zh:'建筑与土木工程承包商'},'Hubungi Pejabat & Sebutharga':{en:'Contact & Quotations',zh:'联系与报价'},
'Sila masukkan nama penuh anda.':{en:'Please enter your full name.',zh:'请输入您的姓名。'},'Sila masukkan nombor telefon untuk dihubungi.':{en:'Please enter a contact phone number.',zh:'请输入联系电话。'},'Sila masukkan nombor telefon yang sah (sekurang-kurangnya 8 digit).':{en:'Please enter a valid phone number (at least 8 digits).',zh:'请输入有效电话号码（至少8位数字）。'},'Sila nyatakan lokasi tapak projek anda.':{en:'Please enter your project site location.',zh:'请填写项目地点。'},'Sila nyatakan keterangan ringkas keperluan projek anda.':{en:'Please briefly describe your project requirements.',zh:'请简要说明项目需求。'},
'Laman rasmi Pertama Jaya Construction & Engineering Sdn Bhd (1411274-D). Pembinaan bangunan, jambatan, saliran dan loji STP.':{en:'Official website of Pertama Jaya Construction & Engineering Sdn Bhd (1411274-D). Building, bridge, drainage and STP services.',zh:'Pertama Jaya Construction & Engineering Sdn Bhd（1411274-D）官方网站。提供建筑、桥梁、排水及污水处理服务。'},
'Skop kerja pembinaan rumah/kilang, jambatan, saliran pembetungan, slab gas, ubah suai dan servis loji kumbahan.':{en:'Housing and factory construction, bridges, drainage, gas protection slabs, renovations and sewage plant services.',zh:'住宅与厂房施工、桥梁、排水、燃气保护板、翻新及污水处理厂服务。'},
'Galeri foto dokumentasi tapak pembinaan dan senarai rekod projek Pertama Jaya Construction & Engineering.':{en:'Construction-site image gallery and project records of Pertama Jaya Construction & Engineering.',zh:'Pertama Jaya Construction & Engineering 工地图片与项目记录。'},
'Hubungi James di +60 12-434 2290 atau talian pejabat +60 6-270 0490 untuk pertanyaan sebutharga projek anda kepada Pertama Jaya.':{en:'Contact James on +60 12-434 2290 or the office on +60 6-270 0490 for a Pertama Jaya project quotation.',zh:'请联系 James（+60 12-434 2290）或办公室（+60 6-270 0490）咨询 Pertama Jaya 项目报价。'},
'Pengenalan Pertama Jaya Construction & Engineering Sdn Bhd (1411274-D), objektif korporat, falsafah syarikat, misi, visi dan kepimpinan.':{en:'About Pertama Jaya Construction & Engineering Sdn Bhd (1411274-D): objectives, values, mission, vision and leadership.',zh:'了解 Pertama Jaya Construction & Engineering Sdn Bhd（1411274-D）的目标、价值观、使命、愿景与领导。'},
'404 Halaman Tidak Dijumpai':{en:'404 Page Not Found',zh:'404 找不到页面'},'Penyelesaian Pembinaan & Kejuruteraan untuk Projek Anda.':{en:'Construction & engineering solutions for your project.',zh:'为您的项目提供建筑与工程方案。'}
};
